#!/bin/bash
#PBS -P CFP05-CF-002
#PBS -j oe
#PBS -k oed
#PBS -N colosseum-lerobot-molmoact2-so101-soccer-red_bowl-40episodes
#PBS -q auto
#PBS -l select=1:ngpus=1
#PBS -l walltime=3:00:00

cd $PBS_O_WORKDIR

image="/app1/common/singularity-img/hopper/pytorch/pytorch_2.7.0_cuda_12.8.sif"

module load singularity

LOG_DIR='./logs/molmoact2-so101-soccer-red_bowl-40episodes'
mkdir -p $LOG_DIR

singularity exec -e --nv \
--env HF_HOME=/scratch/e1583535/cache \
--env TMPDIR=/scratch/e1583535/tmp \
--env TEMP=/scratch/e1583535/tmp \
--env TMP=/scratch/e1583535/tmp \
$image bash << 'EOF' > $LOG_DIR/stdout.$PBS_JOBID.log 2> $LOG_DIR/stderr.$PBS_JOBID.log

mkdir -p /scratch/e1583535/tmp

if [ -d "/scratch/e1583535/virtualenvs/lerobot-cu128" ]; then
    source /scratch/e1583535/virtualenvs/lerobot-cu128/bin/activate
fi

echo "Starting policy worker at $(date)"
echo "Running on host: $(hostname)"
echo "GPU info:"
nvidia-smi --query-gpu=name,memory.total,memory.free --format=csv,noheader,nounits || echo "No GPU detected"

bash scripts/molmoact2/train_so101_soccer_red_bowl_40episodes.sh
EOF