# @package _global_

defaults:
  - override /model: g05
  - override /tokenizer: actioncodec
  - override /data: so101_soccer_red_bowl
  - _self_


shard_datasets_by_node: false

use_fsdp: false

fsdp_sharding_strategy: hybrid
fsdp_mixed_precision: false
fsdp_prefetch: true
fsdp_reshard_after_forward: true


vlm:
  cotrain: false
  batch_size: ${model.batch_size}
  num_workers: 4
  vlm_batch_ratio: 0.2
  loss_weight: 1.0

datastatics_path: null


logger:
  type: wandb
  mode: online
  workspace: null


deploy_checkpoint:
  enabled: true


tokenizer:

  vq_config:

    block_wise_autoregressive: false
    block_size: 8
    num_residuals: 2

    rule_based_key_patterns:
      - gripper

    rule_based_binarize_threshold: 0.0

    use_group_markers: true
    group_order_shuffle: false
    dropout_noop_parts: true

    absent_key_fill_value: -100.0

    parts_meta:
      left_control: 9
      left_gripper: 1
      right_control: 9
      right_gripper: 1
      lower_body: 7

    model_arch:
      codebook_size: 4096


model:

  # Fine-tune from G0.5 base
  pretrained_ckpt: checkpoints/g05-base/checkpoints/model_state_dict.pt

  # 1 GPUs x 16/GPU = global batch 16
  batch_size: 1

  num_workers: 8
  prefetch_factor: 2

  # Same sample budget as your MolmoAct2/pi05/GR00T runs
  max_epochs: null
  max_steps: 921

  grad_accumulation_steps: 16

  # Start from the official R1Pro G0.5 fine-tuning LR
  learning_rate: 4.0e-5
  weight_decay: 0.03

  warmup_ratio: 0.05
  warmup_steps: null

  lr_scheduler_type: cosine
  lr_min_ratio: 0.0
  constant_end_ratio: 0.08

  enable_bf16_training: true
  use_8bit_optimizer: false


  processor:

    vlm_input_action_norm_default_mode: null
    vlm_input_action_norm_exception_mode: null

    tokenizer_params:
      local_files_only: true
      num_input_cameras: 2

    num_output_cameras: 2

    camera_size_config:
      exterior: [256, 256]
      wrist_right: [256, 256]


    action_filter:
      _target_: g05.data_processor.transforms.action_filter.DummyActionFilter


    action_state_merger:
      _target_: g05.data_processor.transforms.action_state_merger.GroupedPaddingMerger

      max_action_shape_meta: ${oc.load:configs/data/parts_meta/so101.yaml,parts_meta}
      max_state_shape_meta: ${oc.load:configs/data/parts_meta/so101.yaml,parts_meta}
      merge_spec: ${oc.load:configs/data/parts_meta/so101.yaml,merge_spec}

      merge: true


  model_arch:

    vision_lr_multiplier: 0.1

    action_dim: 27
    proprio_dim: 27

    fm:
      num_flow_samples: 4

    ar:
      block_wise_autoregressive: false

    predict_cot: false

    input_preprocessor:
      pred_eov: false